### ISSUE TITLE
Bad argument name

### ISSUE THREAD

**Issue by iDevelopper** [DenDmitriev/DominantColors#17]
Version 1.1.6

In PreviewiOS.swift, in refreshColors(from uiImage: UIImage?), calling the DominantColors function with the time argument (line 186) instead of timeLog causes a compilation error.

**Comment by DenDmitriev** [comment]
Hi

I fixed the arguments in the function the day before and now I'm just solving bugs that came out. Wait a while, the fix will be soon.

**Comment by DenDmitriev** [comment]
I solved the errors that occurred. Use version 1.1.7. Please close issues if everything is ok after the update.
I also added the ability to receive immediately `UIColor` or `Color.Resolved`. See ReadMe.

**Comment by iDevelopper** [comment]
Thanks!
