### ISSUE TITLE
EXC_BAD_ACCESS in ExtractColors

### ISSUE THREAD

**Issue by iDevelopper** [DenDmitriev/DominantColors#19]
Sometimes the application crashes. I think the last time it was with this image.

![v4_179298-329992](https://github.com/DenDmitriev/DominantColors/assets/1782450/9436f044-a285-492a-9ff4-309438bb327d)

<img width="835" alt="Capture d’écran 2024-05-12 à 15 46 30" src="https://github.com/DenDmitriev/DominantColors/assets/1782450/4810c810-5aba-4287-a7a5-bbe062cb1e56">

My code is:

```Swift
            let averageColor = try DominantColors.averageColors(image: image, count: 1, sorting: .frequency)
            let dominantColors = try DominantColors.dominantColors(image: image, quality: .best, algorithm: .CIE76, maxCount: 4, options: [.excludeWhite, .excludeBlack], sorting: .frequency, deltaColors: 10, resultLog: false, timeLog: false)
```

What can I do?

Thanks!

**Comment by DenDmitriev** [comment]
Привет

Thanks for the bug report. I have not previously tested images that have gray scales. I took this into account in the code for version 1.1.8. In image data using gammas such as sRGB, there are 4 channels (red, green, blue, transparency) for color and 2 channels for gray (the first level of gray brightness, the second level of transparency). Therefore, an error occurred when reading the data array. Update the version to 1.1.8 and close the issue if everything is ok.

I recommend you use the following call:
```swift
let dominantColors = try image.dominantColors(max: 6, options: [.excludeBlack, .excludeWhite])
```
This will be much faster in terms of the algorithm's running time and shorter in code.

I see that you use one medium color. You probably need contrasting colors to create a text block. If so, then try the following method of the `ContrastColors` library:
```swift
let contrastColors = ContrastColors(colors: dominantColors.map({ $0.cgColor }))
let backgroundColor = contrastColors?.background
let primaryColor = contrastColors?.primary
let secondaryColor = contrastColors?.secondary
```
You can get this result used `backgroundColor ` for background, `primaryColor` for title and `secondaryColor` for subtitle:

<img width="272" alt="Снимок экрана 2024-05-13 в 08 49 30" src="https://github.com/DenDmitriev/DominantColors/assets/65191747/40132d86-73bf-457e-9c56-ce7e30670945">
<img width="271" alt="Снимок экрана 2024-05-13 в 08 50 04" src="https://github.com/DenDmitriev/DominantColors/assets/65191747/9e90b9a5-dc78-4c42-9155-6bfeee139560">

**Comment by iDevelopper** [comment]
Hello,

Thank you for your responsiveness !

I tested your demo project with this image and I don't have any crashes. Weird.

In my application (https://apps.apple.com/fr/app/shout-radios/id1474971083), I use averageColor for the player background and 4 other colors with alpha component < 1.0 to color moving circles initially placed randomly on the view, not for text.

```swift
let dominantColors = try image.dominantColors(max: 6, options: [.excludeBlack, .excludeWhite])
```
Do you mean I should use .fair for quality and .CIE94 for algorithm?

```swift
        guard let averageColor = try? DominantColors.averageColors(image: image, count: 1, sorting: .frequency) else { return }
        guard let dominantColors = try? DominantColors.dominantColors(image: image, quality: .best, algorithm: .CIE94, maxCount: 4, options: [.excludeWhite, .excludeBlack], sorting: .frequency, resultLog: false, timeLog: false) else { return }
```

**Comment by DenDmitriev** [comment]
Yes, fair or high quality is fast. You can enable log for viewing to compare times. In my tests, I did not notice a significant difference in performance results.

CIE94 uses a more advanced color difference formula than CIE76. It takes into account more nuances of human perception of color differences compared to mathematical ones.

**Comment by iDevelopper** [comment]
Thank you for everything!
