### ISSUE TITLE
Return `Color.Resolved`

### ISSUE THREAD

**Issue by sindresorhus** [DenDmitriev/DominantColors#8]
The type is better than CGColor in every way. It's a simple struct, fixed color space, Codable, etc. The only problem is that it requires macOS 14.

https://developer.apple.com/documentation/swiftui/color/resolved

**Comment by DenDmitriev** [comment]
It's a good idea to expand. I will add support as soon as possible.  iOS is also from version 17

**Comment by sindresorhus** [comment]
Yes, you can see the required OS versions in the above link.

**Comment by DenDmitriev** [comment]
I added the ability to get `Color.Resolved`, `UIColor` or `NSColor`. Use 1.1.7 version.
```swift
let colorsResolved =  try? DominantColors.dominantColorsResolved(image: cgImage)
```
