### ISSUE TITLE
SPM Package.swift missing platforms key

### ISSUE THREAD

**Issue by iDevelopper** [DenDmitriev/DominantColors#9]
Minimum deployment version for each supported platforms is not set.

So there are compilation errors for iOS.

Showing Recent Issues
/Users/patrickbodet/Library/Developer/Xcode/DerivedData/ShoutRadiosSwift-crcuihvbcexsvcgzdwnxbugtvcxv/SourcePackages/checkouts/DominantColors/Sources/DominantColors/GradientColors.swift:16:30: Type 'CGColor' has no member 'clear'

/Users/patrickbodet/Library/Developer/Xcode/DerivedData/ShoutRadiosSwift-crcuihvbcexsvcgzdwnxbugtvcxv/SourcePackages/checkouts/DominantColors/Sources/DominantColors/GradientColors.swift:18:29: Type 'CGColor' has no member 'clear'

/Users/patrickbodet/Library/Developer/Xcode/DerivedData/ShoutRadiosSwift-crcuihvbcexsvcgzdwnxbugtvcxv/SourcePackages/checkouts/DominantColors/Sources/DominantColors/GradientColors.swift:42:27: 'init(red:green:blue:alpha:)' is only available in iOS 13.0 or newer

/Users/patrickbodet/Library/Developer/Xcode/DerivedData/ShoutRadiosSwift-crcuihvbcexsvcgzdwnxbugtvcxv/SourcePackages/checkouts/DominantColors/Sources/DominantColors/GradientColors.swift:58:24: Type 'CGColor' has no member 'clear'

/Users/patrickbodet/Library/Developer/Xcode/DerivedData/ShoutRadiosSwift-crcuihvbcexsvcgzdwnxbugtvcxv/SourcePackages/checkouts/DominantColors/Sources/DominantColors/GradientColors.swift:62:30: Type 'CGColor' has no member 'clear'

/Users/patrickbodet/Library/Developer/Xcode/DerivedData/ShoutRadiosSwift-crcuihvbcexsvcgzdwnxbugtvcxv/SourcePackages/checkouts/DominantColors/Sources/DominantColors/GradientColors.swift:64:29: Type 'CGColor' has no member 'clear'

/Users/patrickbodet/Library/Developer/Xcode/DerivedData/ShoutRadiosSwift-crcuihvbcexsvcgzdwnxbugtvcxv/SourcePackages/checkouts/DominantColors/Sources/DominantColors/GradientColors.swift:89:27: 'init(red:green:blue:alpha:)' is only available in iOS 13.0 or newer

Thanks

**Comment by iDevelopper** [comment]
I saw that there was a branch named add-iOS-support. Is it not possible to merge it into the Master branch?

**Comment by DenDmitriev** [comment]
Good afternoon.
I was busy with another project. Try to find time to solve these shortcomings. Thank you for writing about it. I'll let you know as a result.

**Comment by DenDmitriev** [comment]
I updated the versions and now everything should work. Please check at your place. Current version 1.1.1. Please write about the results. Thank you for letting me know.

**Comment by iDevelopper** [comment]
Awesome ! Everything works fine for me. Thanks again !

**Comment by DenDmitriev** [comment]
That's great! I will make a demo project on iOS and put it in the package
to automatically check when updating.

Дмитриев Денис
https://dendmitriev.ru <https://www.facebook.com/denis.dmitriev.714>


Чт, 4 апр. 2024 г. в 14:41, Patrick ***@***.***>:
